### ISSUE TITLE
struct with rules for members

### ISSUE THREAD

**Issue by drahnr** [pest-parser/ast#15]
While the csv example is nice, it is kind of hard to use with more complex examples:

```
fc1 = { ALPHANUM+ }
rel = { ( "+" | "-" | "/" | "x" | "++" ) }
fc0 = { ALPHANUM+ }
operation = { fc0 ~ rel ~ fc1? }
```
which yields 3 rules, but I only want to generate on struct of that:

```rust

#[derive(Debug)]
enum Operation {
Plus, Minus, Mpy, Div, Inc
}

    fn span_into_str(span: Span) -> &str {
        span.as_str()
    }

#[derive(Debug,FromPest)]
#[pest_ast(rule(Rule::operation))]
struct CalcOp {
     // how to make this bind to a rule explicitly?
      #[pest_ast(inner(with(span_into_str), with(str::parse), with(Result::unwrap)))]
      operand1: u64,
      #[pest_ast(inner(with(span_into_str), with(str::parse), with(Result::unwrap)))]
      operation: Operation, 
      #[pest_ast(inner(with(span_into_str), with(str::parse), with(Option::ok)))] // this does not work, but that's not the point here :)
      operand2 : Option<u64>
}
```

I am not exactly clear how I would go about matching the items/members of the struct against specific rules?
Or is it mandatory to have a type for each and every rule?

Thanks!

**Comment by CAD97** [comment]
The _easiest_ way (what the derive directly supports) is to have a type corresponding to each _non-silent_ production in the grammar. You can also specify the rule that an inner match expects with `#[pest_ast(inner(rule(Rule::fc1), with(span_into_str), ..)]`.

If things get complicated, you can always `impl FromPest` for whatever types you need to manually as well.

**Comment by drahnr** [comment]
Implemting it manually is quite a bit of ugly boilerplate, and it also requires all my error types to be `Void` typed where I optimally would like to use `Failure` to enhance with info regarding line and col.
So to my understanding - with those constraints - I am back to implemting `FromPest` manually for all my types.

It would be nice to be able to eval multiple rules to the same struct :)

**Comment by drahnr** [comment]
Did the implementations manually, as recommended
